[DBus (name = "org.freedesktop.Telepathy.Error")]
public errordomain Telepathy.Error {
	ALREADY_CONNECTED,
	AUTHENTICATION_FAILED,
	BUSY,
	CANCELLED,
	CAPTCHA_NOT_SUPPORTED,
	CONFUSED,
	CONNECTION_FAILED,
	CONNECTION_LOST,
	CONNECTION_REFUSED,
	CONNECTION_REPLACED,
	DISCONNECTED,
	DOES_NOT_EXIST,
	EMERGENCY_CALLS_NOT_SUPPORTED,
	ENCRYPTION_ERROR,
	ENCRYPTION_NOT_AVAILABLE,
	INSUFFICIENT_BALANCE,
	INVALID_ARGUMENT,
	INVALID_HANDLE,
	NETWORK_ERROR,
	NO_ANSWER,
	NOT_AVAILABLE,
	NOT_CAPABLE,
	NOT_IMPLEMENTED,
	NOT_YET,
	NOT_YOURS,
	OFFLINE,
	PERMISSION_DENIED,
	PICKED_UP_ELSEWHERE,
	REGISTRATION_EXISTS,
	REJECTED,
	RESOURCE_UNAVAILABLE,
	SERVICE_BUSY,
	SERVICE_CONFUSED,
	SOFTWARE_UPGRADE_REQUIRED,
	TERMINATED,
	WOULD_BREAK_ANONYMITY
}

[DBus (name = "org.freedesktop.Telepathy.Error.Cert")]
public errordomain Telepathy.CertError {
	EXPIRED,
	FINGERPRINT_MISMATCH,
	HOSTNAME_MISMATCH,
	INSECURE,
	INVALID,
	LIMIT_EXCEEDED,
	NOT_ACTIVATED,
	NOT_PROVIDED,
	REVOKED,
	SELF_SIGNED,
	UNTRUSTED
}

[DBus (name = "org.freedesktop.Telepathy.Error.Channel")]
public errordomain Telepathy.ChannelError
{
	BANNED,
	FULL,
	INVITE_ONLY,
	KICKED
}

[DBus (name = "org.freedesktop.Telepathy.Error.Media")]
public errordomain Telepathy.MediaError
{
	CODECS_INCOMPATIBLE,
	STREAMING_ERROR,
	UNSUPPORTED_TYPE
}
